version: "3.1"
language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.7

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  epochs: 100
assistant_id: 20250121-124024-wide-oregano
